kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: pytorch-demo
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: image
  command: "python3 src/main.py"

  tensorboard:
    enabled: true

  types:
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 1
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 0
            type: gpu
            product: NVIDIA-A100-SXM4-80GB-MIG-3g.40gb




