# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: ray-lite
  context: ray-lite # ray-lite folder
  dockerfile: ./Dockerfile

spec:
  engineName: "max-3760"
  operator: kuberay
  image: ray-lite
  rayVersion: "2.36.1" # must match the base image in ray-lite/Dockerfile
  command: "python3 -u main.py 5" # 5 = seconds of logs per node

  debug:
    jupyter: false

  tensorboard: # optional, disabled by default
    enabled: false

  types:
    Head:
      resources:
        cpus: 1
        ramRatio: 1
    Workers:
      - name: cpu-workers
        # count: 0
        resources:
          cpus: 1
          ramRatio: 2
          shmSizeGB: 0

