kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: jax-demo
  context: jax-demo # jax-demo folder
  dockerfile: ./Dockerfile

spec:
  operator: jax
  image: jax-demo
  command: "env"
  tensorboard:
    enabled: true
  types:
    worker:
      count: 1
      resources:
        cpus: 2
        ramRatio: 1 # = 4 cpus * 4 ramRatios = 16GB
        shmSizeGB: 0
        accelerators:
          gpu:
            count: 0
            type: gpu
            product: Tesla-V100-SXM3-32GB



