kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: pytorch-demo
  context: pytorch-demo # folder
  dockerfile: ./Dockerfile

spec:
  operator: jax
  image: jax-demo
  command: |
   for i in {0..10000}
   do
   if [ $(($i % 2)) -eq 0  ]
   then
        echo "Number: $i and is even."
   else
        echo "Number: $i and is odd."
   fi
  tensorboard:
    enabled: true
  types:
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 1
        shmSizeGB: 0
        accelerators:
          gpu:
            count: 0
            type: gpu
            product: Tesla-V100-SXM3-32GB


