kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: raytune-pong
  context: raytune-pong # raytune-pong folder
  dockerfile: ./Dockerfile

spec:
  operator: kuberay
  image: raytune-pong
  command: "python main.py"

  debug:
    jupyter: false

  tensorboard: # optional, disabled by default
    enabled: true

  types:
    Head:
      resources:
        cpus: 1
        ramRatio: 1
        accelerators: # optional
          gpu:
            count: 0
            product: NVIDIA-A100-SXM4-40GB
            type: gpu

    Workers:
      - name: cpu-workers
        count: 1
        resources:
          cpus: 1
          ramRatio: 1
          shmSizeGB: 0

